from pathlib import Path

p=Path('app.py')
s=p.read_text()
s=s.replace('APP_VERSION = "25.14"','APP_VERSION = "25.15"',1)
old=''' const qualified=source.map(x=>({x,e:topSetupEvaluation(x)})).filter(z=>z.e.hardPass&&z.e.score>=55).sort((a,b)=>b.e.score-a.e.score);\n const rows=qualified.slice(0,6);\n if(st)st.textContent=rows.length?`${rows.length} candidate${rows.length===1?"":"s"} · click to validate`:"No A-quality setup currently";\n if(!rows.length){\n   const msg=automaticTopSetupsRunning?"Scanning all supportive sectors / themes…":"No market-wide A-quality setup currently. The scanner will not force a pick.";\n   g.innerHTML=`<div class="topSetupsEmpty">${msg}</div>`;return\n }\n g.innerHTML=rows.map(({x,e},i)=>{\n const va=e.va,complete=setupCompleteness(x,e),label=e.score>=80&&va?.strength==="CONFIRMED"&&e.stratPass&&complete.complete?"A+ SETUP":"A-QUALITY WATCH",alignmentLabel=e.alignment==="EARLY"?"EARLY ALIGNMENT":"FULL ALIGNMENT";\n const pc=e.premiumSupport?.best_contract;'''
new=''' const evaluated=source.map(x=>({x,e:topSetupEvaluation(x)}));\n const qualified=evaluated.filter(z=>z.e.hardPass&&z.e.score>=55).sort((a,b)=>b.e.score-a.e.score);\n // Do not weaken the A-quality gate just to force a trade. When no full setup\n // passes, surface premium-floor opportunities from the already-vetted finalist\n // universe as a separate WATCH state so the trader can stalk the contract while\n // waiting for stock/structure confirmation.\n const premiumWatch=evaluated.filter(z=>{\n   const pc=z.e.premiumSupport?.best_contract;\n   if(!pc||z.e.hardPass)return false;\n   const state=String(pc.state||"");\n   const ps=Number(pc.premium_support_score||pc.score||0);\n   return ["REVERSAL CONFIRMED","AT SUPPORT","NEAR SUPPORT"].includes(state)&&ps>=60;\n }).sort((a,b)=>Number(b.e.premiumSupport?.best_contract?.premium_support_score||0)-Number(a.e.premiumSupport?.best_contract?.premium_support_score||0));\n const usingPremiumWatch=qualified.length===0&&premiumWatch.length>0;\n const rows=(usingPremiumWatch?premiumWatch:qualified).slice(0,6);\n if(st)st.textContent=rows.length?(usingPremiumWatch?`${rows.length} premium support watch${rows.length===1?"":"es"} · stock confirmation pending`:`${rows.length} candidate${rows.length===1?"":"s"} · click to validate`):"No A-quality setup or premium-support watch currently";\n if(!rows.length){\n   const msg=automaticTopSetupsRunning?"Scanning all supportive sectors / themes…":"No market-wide A-quality setup or qualified premium-support watch currently. The scanner will not force a pick.";\n   g.innerHTML=`<div class="topSetupsEmpty">${msg}</div>`;return\n }\n g.innerHTML=rows.map(({x,e},i)=>{\n const va=e.va,complete=setupCompleteness(x,e),label=usingPremiumWatch?"PREMIUM SUPPORT WATCH":(e.score>=80&&va?.strength==="CONFIRMED"&&e.stratPass&&complete.complete?"A+ SETUP":"A-QUALITY WATCH"),alignmentLabel=e.alignment==="EARLY"?"EARLY ALIGNMENT":"FULL ALIGNMENT";\n const pc=e.premiumSupport?.best_contract;'''
assert old in s, 'renderTopSetups block not found'
s=s.replace(old,new,1)
# Make the watch state explicit on the card without changing the underlying score.
old2=''' const badges=(e.reasons||[]).map(r=>`<span class="topSetupBadge">${r}</span>`).join("");'''
new2=''' const watchBadge=usingPremiumWatch?`<span class="topSetupBadge" style="border-color:#a16207;color:#fbbf24">Stock confirmation pending</span>`:"";\n const badges=watchBadge+(e.reasons||[]).map(r=>`<span class="topSetupBadge">${r}</span>`).join("");'''
assert old2 in s, 'badges block not found'
s=s.replace(old2,new2,1)
p.write_text(s)

r=Path('README.txt')
rs=r.read_text()
r.write_text('''v25.15 — PREMIUM SUPPORT WATCH FALLBACK\n- Top Setups no longer goes completely blank when no stock passes the full A-quality hard gate but a finalist has a genuinely strong premium-floor setup.\n- A-quality gating is unchanged. When zero A-quality names exist, the UI may instead show up to six PREMIUM SUPPORT WATCH cards from the already-vetted finalist universe when the contract is REVERSAL CONFIRMED / AT SUPPORT / NEAR SUPPORT with Premium Support Score >=60.\n- Premium watches are explicitly labeled "Stock confirmation pending" so they are scouting candidates, not trade calls.\n\n'''+rs)
