from pathlib import Path
p=Path('app.py')
s=p.read_text()
s=s.replace('APP_VERSION = "25.29"','APP_VERSION = "25.30"',1)
# Reduce premium from dominant scoring factor to entry-quality modifier.
s=s.replace('''   if(ps>=80){raw+=15;reasons.push([`Premium ${pc.state||"support"} · ${ps.toFixed(0)}`,"good"]);}\n   else if(ps>=65){raw+=10;reasons.push([`Premium near support · ${ps.toFixed(0)}`,"good"]);}\n   else if(ps>=50){raw+=5;reasons.push([`Premium base developing · ${ps.toFixed(0)}`,"warn"]);}\n   else if(pc?.state==="AWAY FROM SUPPORT"){raw-=4;reasons.push(["Premium away from support","warn"]);}''','''   if(ps>=80){raw+=6;reasons.push([`Premium entry attractive · ${ps.toFixed(0)}`,"good"]);}\n   else if(ps>=65){raw+=4;reasons.push([`Premium near support · ${ps.toFixed(0)}`,"good"]);}\n   else if(ps>=50){raw+=2;reasons.push([`Premium entry fair · ${ps.toFixed(0)}`,"warn"]);}\n   else if(pc?.state==="AWAY FROM SUPPORT"){raw-=2;reasons.push(["Premium extended vs support","warn"]);}''',1)
# Top Setups no longer falls back to premium-only candidates. Nearest misses remain for transparency.
start=s.index(' // Keep the full A-quality gate intact. If none pass, surface strong premium')
end=s.index(' updateSpeculativeSignalsVisibility(qualified.length);',start)
s=s[:start]+''' // Premium support is an entry-quality overlay, not a setup gate. A strong\n // underlying setup remains visible even when its option premium is not near\n // a historical floor. Liquidity/Tradable status remains a hard contract gate.\n const usingPremiumWatch=false;\n'''+s[end:]
s=s.replace('const rows=(usingPremiumWatch?premiumWatch:qualified).slice(0,6);','const rows=qualified.slice(0,6);',1)
s=s.replace('if(st)st.textContent=rows.length?(usingPremiumWatch?`${rows.length} premium support watch${rows.length===1?"":"es"} · stock confirmation pending`:`${rows.length} candidate${rows.length===1?"":"s"} · click to validate`):"No A-quality setup or premium-support watch currently";','if(st)st.textContent=rows.length?`${rows.length} candidate${rows.length===1?"":"s"} · premium shown as entry quality` : "No A-quality setup currently";',1)
s=s.replace('const msg=automaticTopSetupsRunning?"Scanning all supportive sectors / themes…":"No market-wide A-quality setup or qualified premium-support watch currently. The scanner will not force a pick.";','const msg=automaticTopSetupsRunning?"Scanning all supportive sectors / themes…":"No market-wide A-quality setup currently. Premium state does not determine qualification.";',1)
s=s.replace('const label=usingPremiumWatch?"PREMIUM SUPPORT WATCH":(e.score>=80&&va?.strength==="CONFIRMED"&&e.stratPass&&complete.complete?"A+ SETUP":"A-QUALITY WATCH")','const label=(e.score>=80&&va?.strength==="CONFIRMED"&&e.stratPass&&complete.complete?"A+ SETUP":"A-QUALITY WATCH")',1)
# Early turns: premium is no longer required. Attempt enrichment, but keep candidate if absent/away.
s=s.replace('if(st)st.textContent=`Checking premium support on ${shortlist.length} early-turn candidates…`;','if(st)st.textContent=`Adding premium entry context to ${shortlist.length} early-turn candidates…`;',1)
s=s.replace('''       const r=await fetch(`/api/premium-support/${encodeURIComponent(x.ticker)}?direction=bullish`);\n       const j=await r.json();\n       if(!r.ok||!j.ok)return;\n       const pc=j.best_contract;if(!pc)return;\n       if(!["REVERSAL CONFIRMED","AT SUPPORT","NEAR SUPPORT"].includes(String(pc.state||"")))return;\n       results.push({x,pc,fq,tq,fIn,tIn,source});\n     }catch(e){}''','''       const r=await fetch(`/api/premium-support/${encodeURIComponent(x.ticker)}?direction=bullish`);\n       const j=await r.json();\n       const pc=(r.ok&&j.ok)?j.best_contract:null;\n       results.push({x,pc,fq,tq,fIn,tIn,source});\n     }catch(e){results.push({x,pc:null,fq,tq,fIn,tIn,source})}''',1)
s=s.replace('earlyTurnWatchData=results.sort((a,b)=>Number(b.pc.premium_support_score||0)-Number(a.pc.premium_support_score||0));','earlyTurnWatchData=results.sort((a,b)=>earlyTurnScore(b.x)-earlyTurnScore(a.x));',1)
s=s.replace('"No early-turn candidates currently have a supportive premium base."','"No early-turn candidates currently meet the RRG/sector-turn criteria."',1)
s=s.replace('''   const premiumStateClass={"REVERSAL CONFIRMED":"instGood","AT SUPPORT":"instGood","NEAR SUPPORT":"instWarn"}[pc.state]||"";''','''   const premiumStateClass=pc?({"REVERSAL CONFIRMED":"instGood","AT SUPPORT":"instGood","NEAR SUPPORT":"instWarn","AWAY FROM SUPPORT":"instBad"}[pc.state]||""):"";\n   const premiumLine=pc?`<div class="topSetupTrigger" style="margin-top:7px">PREMIUM ENTRY · <b>${pc.expiration} $${Number(pc.strike).toFixed(0)} ${String(pc.type||"").toLowerCase().startsWith("p")?"P":"C"} · $${Number(pc.mid||0).toFixed(2)} · <span class="${premiumStateClass}">${pc.state}</span></b><div class="tiny">Entry-quality overlay · support $${Number(pc.support_low).toFixed(2)}–$${Number(pc.support_high).toFixed(2)} · score ${Number(pc.premium_support_score||0).toFixed(0)}/100</div></div>`:`<div class="topSetupTrigger" style="margin-top:7px">PREMIUM ENTRY · <b>not required for signal</b></div>`;''',1)
old='''     <div class="topSetupTrigger" style="margin-top:7px">PREMIUM · <b>${pc.expiration} $${Number(pc.strike).toFixed(0)} ${String(pc.type||"").toLowerCase().startsWith("p")?"P":"C"} · $${Number(pc.mid||0).toFixed(2)} · <span class="${premiumStateClass}">${pc.state}</span></b><div class="tiny">support $${Number(pc.support_low).toFixed(2)}–$${Number(pc.support_high).toFixed(2)} · ${pc.distance_from_support_pct==null?"—":Number(pc.distance_from_support_pct).toFixed(1)+"%"} above floor · ${pc.support_touches||0} tests · score ${Number(pc.premium_support_score||0).toFixed(0)}/100</div></div>'''
s=s.replace(old,'${premiumLine}',1)
s=s.replace('No qualifying early-turn / premium-base candidates right now. This list is intentionally speculative — it looks for names (or whole sectors) still reading Lagging whose RRG tail has just turned NE, with an option premium sitting near its own historical floor.','No qualifying early-turn candidates right now. This list is intentionally speculative — it looks for names (or whole sectors) still reading Lagging whose RRG tail has just turned NE. Premium support is shown only as entry-quality context and is not required.',1)
p.write_text(s)

r=Path('README.txt')
rs=r.read_text()
r.write_text('''v25.30 — PREMIUM SUPPORT BECOMES ENTRY-QUALITY OVERLAY\n- Removed premium-near-support as a qualification requirement/fallback gate. Top Setups qualification remains driven by RRG trajectory, liquid/tradable options, value/structure, STRAT and the broader confluence score.\n- Reduced premium-support scoring weight so an attractive premium improves ranking but cannot dominate a strong underlying setup; being away from support is a small entry-quality penalty rather than automatic exclusion.\n- Early Turn / Speculative Signals no longer require AT SUPPORT / NEAR SUPPORT to appear. Premium history is fetched opportunistically and displayed as entry context; the early RRG/sector signal survives when premium is normal, extended, or unavailable.\n- Kept liquidity/tradability and genuinely adverse setup conditions as hard gates.\n\n'''+rs)
