from pathlib import Path
p=Path('app.py')
s=p.read_text()
s=s.replace('APP_VERSION = "25.33"','APP_VERSION = "25.34"',1)
old='''async function runEarnings(){\n const st=document.getElementById("estatus");\n st.textContent="Scanning all sectors/themes for recent earnings opportunities…";\n try{\n   const days=document.getElementById("earnDays").value||"5";\n   const response=await fetch(`/api/postearnings-opportunities?days=${encodeURIComponent(days)}`,{headers:{"Accept":"application/json"}});\n   const raw=await response.text();let j;\n   try{j=JSON.parse(raw)}catch(e){throw Error(`Unreadable earnings response (${response.status})`)}\n   if(!response.ok||!j.ok)throw Error(j.error||`Scan failed (${response.status})`);'''
new='''async function runEarnings(){\n const st=document.getElementById("estatus");\n st.textContent="Scanning all sectors/themes for recent earnings opportunities…";\n try{\n   const days=document.getElementById("earnDays").value||"5";\n   let response=null,raw="",j=null,lastErr=null;\n   const waits=[0,2500,6000,12000];\n   for(let attempt=0;attempt<waits.length;attempt++){\n     if(waits[attempt]){st.textContent=`Earnings service restarted or is busy · retrying ${attempt}/${waits.length-1}…`;await new Promise(r=>setTimeout(r,waits[attempt]));}\n     try{\n       response=await window.fetch(`/api/postearnings-opportunities?days=${encodeURIComponent(days)}`,{method:"GET",credentials:"same-origin",headers:{"Accept":"application/json"}});\n       raw=await response.text();j=null;\n       try{j=raw?JSON.parse(raw):null}catch(_e){}\n       if(response.ok&&j?.ok)break;\n       lastErr=new Error(j?.error||`Scan failed (${response.status})`);\n       if(![429,502,503,504].includes(response.status))throw lastErr;\n     }catch(e){\n       lastErr=e;\n       if(attempt===waits.length-1)throw e;\n       continue;\n     }\n   }\n   if(!response||!response.ok||!j?.ok){\n     if(response&&!j)throw Error(`Earnings service returned an unreadable response (${response.status})`);\n     throw lastErr||new Error("Earnings scan failed");\n   }'''
if old not in s:
    raise SystemExit('runEarnings anchor not found')
s=s.replace(old,new,1)
p.write_text(s)
r=Path('README.txt'); rs=r.read_text(); r.write_text('''v25.34 — POST-EARNINGS 502 / INSTANCE-RESTART RESILIENCE\n- Render logs showed the earnings 502 coinciding with the web service restarting: health checks stopped, Gunicorn relaunched, then health recovered. The browser previously surfaced that transient restart as a terminal “Unreadable earnings response (502)” error.\n- Earnings Movers now automatically retries transient 429/502/503/504 responses with bounded backoff (2.5s, 6s, 12s) and tells the user the service is restarting/busy rather than failing immediately.\n- Successful JSON behavior and existing server-side cached/stale-safe earnings logic are unchanged. Non-transient application errors still fail immediately.\n\n'''+rs)
