from pathlib import Path
p=Path('app.py');s=p.read_text()
old='return {"available":True,"score":round(score,1),"state":state,"current_premium":round(px,4),"support_low":round(floor,4),"support_high":round(support_hi,4),"distance_from_support_pct":round(distance,1) if distance is not None else None,"support_touches":touches,"prior_20d_high":round(prior_high,4),"prior_expansion_multiple":round(expansion,2) if expansion is not None else None,"range_compression_ratio":round(compression,2) if compression is not None else None,"reversal_confirmed":reversal,"bars_used":len(clean),"last_bar_date":str(clean[-1].get("t") or "")[:10] or None}'
new='floor_reliable=touches>=2\n    return {"available":True,"score":round(score,1),"state":state,"current_premium":round(px,4),"support_low":round(floor,4),"support_high":round(support_hi,4),"distance_from_support_pct":round(distance,1) if distance is not None else None,"support_touches":touches,"floor_reliable":floor_reliable,"prior_20d_high":round(prior_high,4),"prior_expansion_multiple":round(expansion,2) if expansion is not None else None,"range_compression_ratio":round(compression,2) if compression is not None else None,"reversal_confirmed":reversal,"bars_used":len(clean),"last_bar_date":str(clean[-1].get("t") or "")[:10] or None}'
assert old in s;s=s.replace(old,new,1)
old='const premiumHTML=pc?`<div class="topSetupTrigger" style="margin-top:7px">PREMIUM · <b>${pc.expiration} $${Number(pc.strike).toFixed(0)} ${String(pc.type||"").toLowerCase().startsWith("p")?"P":"C"} · $${Number(pc.mid||0).toFixed(2)} · <span class="${premiumStateClass}">${pc.state}</span></b><div class="tiny">support $${Number(pc.support_low).toFixed(2)}–$${Number(pc.support_high).toFixed(2)} · ${pc.distance_from_support_pct==null?"—":Number(pc.distance_from_support_pct).toFixed(1)+"%"} above floor · ${pc.support_touches||0} tests · prior high $${Number(pc.prior_20d_high||0).toFixed(2)} (${pc.prior_expansion_multiple==null?"—":Number(pc.prior_expansion_multiple).toFixed(1)+"×"}) · score ${Number(pc.premium_support_score||0).toFixed(0)}/100</div></div>`'
new='const floorNote=pc?(pc.floor_reliable===false?"floor unreliable (<2 historical touches)":`${pc.distance_from_support_pct==null?"—":Number(pc.distance_from_support_pct).toFixed(1)+"%"} above floor · ${pc.support_touches||0} tests`):"";\n const premiumHTML=pc?`<div class="topSetupTrigger" style="margin-top:7px">PREMIUM · <b>${pc.expiration} $${Number(pc.strike).toFixed(0)} ${String(pc.type||"").toLowerCase().startsWith("p")?"P":"C"} · $${Number(pc.mid||0).toFixed(2)} · <span class="${premiumStateClass}">${pc.state}</span></b><div class="tiny">support $${Number(pc.support_low).toFixed(2)}–$${Number(pc.support_high).toFixed(2)} · ${floorNote} · prior high $${Number(pc.prior_20d_high||0).toFixed(2)} (${pc.prior_expansion_multiple==null?"—":Number(pc.prior_expansion_multiple).toFixed(1)+"×"}) · score ${Number(pc.premium_support_score||0).toFixed(0)}/100</div></div>`'
assert old in s;s=s.replace(old,new,1)
old="const contract=d.pc?`${d.pc.expiration||''} · ${Number(d.pc.strike).toFixed(0)}${String(d.pc.type||'').toLowerCase().startsWith('p')?'P':'C'} · ${d.cost==null?'—':v26Money(d.cost)}`:'premium loading / unavailable';"
new="const contract=d.pc?`${d.pc.expiration||''} · ${Number(d.pc.strike).toFixed(0)}${String(d.pc.type||'').toLowerCase().startsWith('p')?'P':'C'} · ${d.cost==null?'—':v26Money(d.cost)+'/contract'}`:'premium loading / unavailable';"
assert old in s;s=s.replace(old,new,1)
old="const trigger=Number.isFinite(Number(d.s.trigger))?v26Money(d.s.trigger):'—',inv=Number.isFinite(Number(d.s.invalidation))?v26Money(d.s.invalidation):'—';"
new="const trigger=(d.s.trigger!=null&&Number.isFinite(Number(d.s.trigger)))?v26Money(d.s.trigger):'—',inv=(d.s.invalidation!=null&&Number.isFinite(Number(d.s.invalidation)))?v26Money(d.s.invalidation):'—';"
assert old in s;s=s.replace(old,new,1)
p.write_text(s)
r=Path('README.txt');r.write_text('v26.2b — TRADER BOARD DISPLAY FIXES\n- Labels total option cost explicitly as /contract.\n- Missing trigger/invalidation now render as — rather than JavaScript null -> $0 coercion.\n- One-touch premium floors are labeled unreliable rather than showing misleading huge distance percentages.\n\n'+r.read_text())
